const texts = {
    en: {
        title: "To-Do List",
        placeholderTitle: "Task Title",
        placeholderDescription: "Task Description",
        addButton: "Add task",
        filterAll: "All",
        filterCompleted: "Completed",
        filterIncomplete: "Incomplete",
        chooseAPriority: "Choose a Priority",
        low: "Low",
        medium: "Medium",
        high: "High",
        priority: "Priority",
    },
    pt: {
        title: "Lista de Tarefas",
        placeholderTitle: "Título da Tarefa",
        placeholderDescription: "Descrição da Tarefa",
        addButton: "Adicionar Tarefa",
        filterAll: "Todas",
        filterCompleted: "Concluídas",
        filterIncomplete: "Pendentes",
        chooseAPriority: "Escolha uma Prioridade",
        low: "Baixa",
        medium: "Média",
        high: "Alta",
        priority: "Prioridade",
    },
};
